### ISSUE TITLE
Upgrade to R18

### ISSUE THREAD

**Issue by isaiah** [isaiah/transit-erlang#21]
Erlang/OTP R18-rc1 is out. Has a new time API and variable as map keys.

**Comment by jlouis** [comment]
I'm suggesting we just remove no_maps_support as well. Once 18.0 is out, supporting both no maps and the new Time API is going to be hard. Also, I'd like to move to a world where the library requires 17.x, as there are so many things which are hard to handle otherwise. What do you think?

The deeper problem is that Transit changed format a couple of days ago. This may affect certain parts of the code base. So my plan is to put down a version tag in the repository, backport the things which fixes problems w.r.t the current Transit-spec, while working on a 18.0 branch, which also includes rebar3 support.

**Comment by isaiah** [comment]
What's the significant change cognitech did to the transit-format?

**Comment by jlouis** [comment]
They changed the int boundaries:

https://github.com/cognitect/transit-format/commit/6e192a5bb66ba1c71f9651a6c134519bbaa1f9d9
https://github.com/cognitect/transit-format/commit/c6234ca0f121949437401f8b2d81c584306edbd5

Interestingly, this has no effect on our code base whatsoever, so I guess we were doing it right in the first place anyway. I loaded these new exemplars, and everything still pass...

I had a branch in my repo that started doing more work on 18.x, but I can't remember in what state I left it :/
